-- Baseline: the schema Hibernate (ddl-auto=update) generated from the entities as of
-- 2026-10-06, taken from pg_dump on Postgres 16. Databases created before Flyway are
-- identical to this and are adopted as V1 via spring.flyway.baseline-on-migrate.
-- Free-text and list columns are text / text[] on purpose (real values exceed 255
-- chars); UpdaterComponentApplicationIT.freeTextColumnsAreNotLengthLimited guards this.

CREATE TABLE source_version (
    feed_id         varchar(255) NOT NULL,
    content_hash    varchar(255),
    last_checked_at timestamp(6) with time zone,
    last_updated_at timestamp(6) with time zone,
    CONSTRAINT source_version_pkey PRIMARY KEY (feed_id)
);

-- JMdict
CREATE TABLE vocab_entry (
    ent_seq bigint NOT NULL,
    common  boolean,
    CONSTRAINT vocab_entry_pkey PRIMARY KEY (ent_seq)
);

CREATE TABLE reading (
    id      bigint GENERATED BY DEFAULT AS IDENTITY,
    kanji   boolean,
    text    varchar(255) NOT NULL,
    ent_seq bigint,
    CONSTRAINT reading_pkey PRIMARY KEY (id),
    CONSTRAINT fkpen0rh63p9s9d7w6sip9t5yru FOREIGN KEY (ent_seq) REFERENCES vocab_entry (ent_seq)
);

CREATE TABLE sense (
    id      bigint GENERATED BY DEFAULT AS IDENTITY,
    ent_seq bigint,
    CONSTRAINT sense_pkey PRIMARY KEY (id),
    CONSTRAINT fkalx3bp5h8g9jvlt47s7yyn67g FOREIGN KEY (ent_seq) REFERENCES vocab_entry (ent_seq)
);

CREATE TABLE sense_gloss (
    sense_id bigint NOT NULL,
    gloss    text,
    CONSTRAINT fkh8nqj0nur4ufh2oang6qv9gkh FOREIGN KEY (sense_id) REFERENCES sense (id)
);

CREATE TABLE sense_misc (
    sense_id bigint NOT NULL,
    misc     varchar(255),
    CONSTRAINT fkd834rt5icwkybs48hs40w1eoq FOREIGN KEY (sense_id) REFERENCES sense (id)
);

CREATE TABLE sense_pos (
    sense_id bigint NOT NULL,
    pos      varchar(255),
    CONSTRAINT fklj64f642xrw890puu5wb7tc5q FOREIGN KEY (sense_id) REFERENCES sense (id)
);

-- JMnedict
CREATE TABLE name_entry (
    ent_seq      bigint NOT NULL,
    kanji        text[],
    name_types   text[],
    readings     text[],
    translations text[],
    CONSTRAINT name_entry_pkey PRIMARY KEY (ent_seq)
);

-- Kanji (KanjiDic2 / RADKFILE / KanjiVG)
CREATE TABLE kanji (
    "character"       varchar(255) NOT NULL,
    classical_radical integer,
    codepoint         varchar(255),
    frequency         integer,
    grade             integer,
    jlpt              integer,
    joyo              boolean,
    kunyomi           text[],
    meanings          text[],
    nanori            text[],
    onyomi            text[],
    stroke_count      integer,
    stroke_paths      text[],
    CONSTRAINT kanji_pkey PRIMARY KEY ("character")
);

CREATE TABLE radical (
    "character"  varchar(255) NOT NULL,
    stroke_count integer,
    CONSTRAINT radical_pkey PRIMARY KEY ("character")
);

CREATE TABLE kanji_radical (
    kanji   varchar(255) NOT NULL,
    radical varchar(255) NOT NULL,
    CONSTRAINT kanji_radical_pkey PRIMARY KEY (kanji, radical),
    CONSTRAINT fk39amf2uckytgcqvyd8qcppgdg FOREIGN KEY (kanji) REFERENCES kanji ("character"),
    CONSTRAINT fkihyxqgp0702btf0uw5rpfolwj FOREIGN KEY (radical) REFERENCES radical ("character")
);

-- Tatoeba
CREATE TABLE example_sentence (
    id          bigint NOT NULL,
    english     text,
    index_words text,
    japanese    text NOT NULL,
    source      varchar(255),
    CONSTRAINT example_sentence_pkey PRIMARY KEY (id)
);
